/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    base
    // Apply the Kotlin JVM plugin to add support for Kotlin on the JVM.
    kotlin("jvm") version "1.3.11"

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

tasks.withType<Test> {
    useJUnitPlatform()
    testLogging {
        events("skipped", "failed")
        setExceptionFormat("FULL")
    }
}

dependencies {
    // Use the Kotlin JDK 8 standard library.
    implementation(kotlin("stdlib-jdk8"))

    // Use the Kotlin test library. - junit5
    testImplementation(kotlin("test"))
    testImplementation(kotlin("test-junit5") as String) {
        exclude("org.junit.jupiter")
    }
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.3.1")
    testImplementation(group = "org.assertj", name = "assertj-core", version = "3.8.0")
    testRuntime("org.junit.jupiter:junit-jupiter-engine:5.3.1")
}

application {
    // Define the main class for the application.
    mainClassName = "kata.kotlin.AppKt"
}
